#!/bin/sh
# chkconfig: 123456 90 10
# h5dnsd
#
HOMEDIR=/home/ec2-user
#PYTHON=$HOMEDIR/anaconda/bin/python
PYTHON=/usr/bin/python
APPDIR=$HOMEDIR/HDFServer/dynamic-dns/dns
LOCAL_IP=54.174.38.12
DOMAIN=data.hdfgroup.org

start() {
    cd $APPDIR
    $PYTHON dynamic_dns.py --local_ip=$LOCAL_IP --domain=$DOMAIN &
    echo "Server started."
}

stop() {
    pid=`ps -ef | grep 'dynamic_dns.py' | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Server killed."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/h5dnsd {start|stop|restart}"
    exit 1
esac
exit 0
